services:
  - type: web
    name: school-management-system
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        value: base64:SzVeIfSNZbBv9s25ZijpnJhGXlraDRqATm872mbR49Y=
      - key: APP_NAME
        value: testing
      - key: APP_URL
        value: https://school-management-system-f74n.onrender.com
      - key: ASSET_URL
        value: https://school-management-system-f74n.onrender.com

      # Database (Neon)
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-broad-pine-ae510988-pooler.c-2.us-east-2.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_pU2ZScF7LGNC

      # Mail / Other configs
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: mailhog
      - key: MAIL_PORT
        value: 1025
      - key: MAIL_FROM_ADDRESS
        value: hello@example.com
      - key: MAIL_FROM_NAME
        value: testing

      # File system
      - key: FILESYSTEM_DISK
        value: local

    buildCommand: |
      composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist
      npm install
      npm run build

    startCommand: |
      php artisan migrate --force || true
      php artisan db:seed --force || true
      apache2-foreground
