services:
  - type: web
    name: school-management-system
    env: docker
    plan: free
    region: oregon
    branch: main
    autoDeploy: true

    envVars:
      # Laravel app environment
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://school-management-system-f74n.onrender.com
      - key: ASSET_URL
        value: https://school-management-system-f74n.onrender.com

      # Database connection (from Render database service)
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: school-management-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: school-management-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: school-management-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: school-management-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: school-management-db
          property: password

      # Laravel session and cache
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file

      # Mail (you can set later if needed)
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: mailhog
      - key: MAIL_PORT
        value: 1025
      - key: MAIL_FROM_ADDRESS
        value: hello@example.com
      - key: MAIL_FROM_NAME
        value: school-management-system

databases:
  - name: school-management-db
    plan: free
    region: oregon
